### ISSUE TITLE
Add data source: twingate_group

### ISSUE THREAD

**Issue by alexmensch** [Twingate/terraform-provider-twingate#100]
Arguments

- (Required) `id`
    - This ID can be obtained either directly from the public admin API or referenced via the `twingate_groups` data source in our Provider.

Exported attributes

- `id` (String)
- `name` (String)

GraphQL

```graphql
query {
  group(id: "R3JvdXA6MjM0")
   {
    id
    name
  }
}
```

**Comment by alexmensch** [comment]
We're going to leave this issue closed, and spin off a couple more issues to tackle some more specific changes.
1. Your suggestions on exposing more attributes and filters makes a ton of sense. We'll add this as a new issue to enhance this specific data source. Issues #137 and #138 cover this.
2. We're a bit limited by what's currently available in our own API both around filtering items and a number of upstream constraints on group names, but this doesn't mean we won't be making changes in the future. A different team works on our public Admin API and rather than wait for those changes to be made first, we'd rather ship more limited functionality and enhance it later on.
3. As an additional complication, if the upstream identity provider that we sync from allows for duplicate group names (there's all kinds of odd stuff we have to handle from IdPs) we can't enforce unique names in our system, which means that we can't do what would seem to make most sense, which is pulling a single group by name in this data source. We're going to introduce an alternative solution to looking up a singular group that doesn't entirely depend on the name, but that's still a little ways off in our general roadmap unrelated to our Terraform Provider.
4. One more issue that's at least been partially resolved is that where we _are_ able to enforce uniqueness for objects that we control (connectors & remote networks, for example), we hadn't previously needed to have constraints on these objects, and implementing functionality for the provider is forcing us to make some of those changes in the core product. This is a good example where enforcing new constraints can take some time because it can require customers with existing Twingate deployments to make some changes to resolve conflicts introduced by the new constraint. Issue #136 covers this as an example.
5. Our intent around this data source is that we know that it's extremely limited right now (looking up by the API ID we know isn't incredibly useful), but it serves as a base from which we will add more functionality in the future. Anyone using our provider will be able to start using the data source over a variable or import, and then as we add functionality, it will gradually become more useful.
6. We see these data sources as being a useful component of our overall provider, but what we're actually most excited about is implementing resources for Twingate resources, groups, and other objects so that there's much less reliance on data sources to do something useful with Terraform and Twingate. We haven't mapped out the entire roadmap to get there within the issues that exist in this repo yet, but there's a plan to get there over the next few months.

Hopefully that helps clear some things up and gives you some additional context as to why things are rolling out the way that they are.

**Comment by tjstansell** [comment]
> We're going to leave this issue closed, and spin off a couple more issues to tackle some more specific changes.

Thanks for the detailed reply.  I'll just reply to each point rather that quoting them all over again ...

1. Much appreciated for opening those issues.
2. Whether or not the public API can filter items and whether or not the provider datasource can filter items are orthogonal to one another, IMO.  It is an implementation detail and optimization to rely on the API to filter server side.  That doesn't necessarily mean you can't filter within the provider itself while you wait for the API features to get added.
3. Duplicate group names is not a problem.  The whole point is that we should be able to filter by more than just a name.
4. I'm not sure name uniqueness as a whole is a problem as long as there is _some_ combination of attributes that provide uniqueness.
5. I would argue it's unusable in its current state.  This is different than having minimal functionality and evolving it over time.
6. Sure, provider resources are important, but when writing reusable terraform modules, having datasources to query from is critical.  They're both pretty much a requirement.  And having enough flexibility in those datasources to find the thing you're looking for is key.  And when you have things like synced groups that are created outside of terraform, a datasource for those resources is critical.  Hence my keen interest in this particular datasource type.

Thanks again for the discussion and letting me throw my opinion your way :)
