### ISSUE TITLE
Add data source: twingate_users

### ISSUE THREAD

**Issue by alexmensch** [Twingate/terraform-provider-twingate#102]
Arguments

- None
    - We don’t currently support filtering users via our API, so this initial change will simply present a list of all users in the tenant.

Exported attributes

- A list of user objects with the following information:
    - `id` (String)
    - `email` (String)
    - `firstName` (String)
    - `lastName` (String)
    - `role` (String)

GraphQL

```graphql
query {
  users
   {
    edges {
      node {
        id
        firstName
        lastName
        email
        role
      }
    }
  }
}
```

**Comment by vmanilo** [comment]
hey @alexmensch I have an issue with this requirements, currently terraform schema doesn't support maps with  objects, map values can be simple values (string, bool, number), so I can't define datasource schema in the way that it can produce map with user objects.

We can have map as <user email>: <user id>, or just list of users.

Alternatively we can produce list of users + list of emails, then on client side we could use `zipmap` function to build result map with users https://www.terraform.io/language/functions/zipmap

what do you think?

**Comment by alexmensch** [comment]
- Updated with new `role` attribute
- Changed to output a list of user objects
