### ISSUE TITLE
[connectors] Cannot make new connectors

### ISSUE THREAD

**Issue by tarfeef101** [Twingate/terraform-provider-twingate#113]
Trying to create new connectors, but starting this afternoon (literally this morning it was fine), I get this error:
```
│ Error: failed to update connector with id [id]: A Connector with this name already exists.
```
(they most certainly do not exist already, i even double-checked the console, no connectors in the networks I tried)

**Comment by romankor** [comment]
Can you please tell us the version of the provider you are using ? Did you upgrade the provider recently ?

**Comment by tarfeef101** [comment]
Both 0.1.6 and 0.1.7, been on the former for a while, tried the latter today to see if it would help (it did not)

**Comment by tarfeef101** [comment]
okay, so i managed to get stuff to apply, looks like you cannot have connectors w/ the same name, even if they're in different networks??? did not see this in any docs (nor is it intuitively determined). hopefully either this can be made possible, or at least documented, and perhaps validated in the provider?

**Comment by ekampf** [comment]
@tarfeef101 right now connector names have to be unique for the account. 
We agree with your feedback and will work to change this limitation to the scope of a remote network in the (very) near future.
Will update here when its done
