### ISSUE TITLE
Expose additional read-only attributes for twingate_group and twingate_groups data sources

### ISSUE THREAD

**Issue by alexmensch** [Twingate/terraform-provider-twingate#137]
### Summary

Exposing additional attributes would be helpful in order to differentiate between groups on more information than the name of the group.

The following attributes are currently available from the public Admin API:
- isActive (Boolean)
- type (Enum) [ MANUAL, SYNCED, SYSTEM ]

### Additional exported attributes

- `is_active` (Boolean)
- `type` (String)
- - The set of `type` attribute values must be `[ MANUAL, SYNCED, SYSTEM ]`, corresponding to the public API enum values

### Admin API GraphQL query

query {
  group(id: "R3JvdXA6MjM0")
   {
    id
    name
    isActive
    type
  }
}

**Comment by tjstansell** [comment]
I think that if this issue and #139 are resolved the `twingate_groups` datasource becomes functional for a majority of use-cases.  It requires filtering within terraform, but that should be fine.  Future updates (e.g. #138) would be additional optimizations to reduce the number of API calls or reduce the payload from those API calls, which is great, but not a priority, IMO.

**Comment by alexmensch** [comment]
> I think that if this issue and #139 are resolved the `twingate_groups` datasource becomes functional for a majority of use-cases. It requires filtering within terraform, but that should be fine. Future updates (e.g. #138) would be additional optimizations to reduce the number of API calls or reduce the payload from those API calls, which is great, but not a priority, IMO.

Perfect, yes, we're on the same page here @tjstansell. Appreciate the effort you're putting into the feedback here.
