### ISSUE TITLE
`twingate_groups` datasource - the `name` parameter should be optional

### ISSUE THREAD

**Issue by tjstansell** [Twingate/terraform-provider-twingate#139]
You should be able to get a list of all groups.  #138 would let us optimize this query in the future and let the API filter the results on the server side. #137 will let us get more data to find the group we're looking for based on more attributes which would let us filter things ourselves.  Even without those, we should be able to just query for all groups and get a list of `id` and `name`s.  This, at least, would be a single api call instead of one per group you might be interested in.  And if you know you don't have multiple groups of the same name, you can pretty easily find the `id` of the group you're interested in.

**Comment by alexmensch** [comment]
Hey @tjstansell the intent in #99 was to make the `name` parameter optional. @vmanilo can you confirm that that's the case? If not, we need to make sure we fix that.
