### ISSUE TITLE
Terraform import on Twingate resources does not import protocols

### ISSUE THREAD

**Issue by emrul** [Twingate/terraform-provider-twingate#145]
terraform import on a Twingate resource does not import the protocols so a subsequent terraform plan will always plan a change.

Reproduction steps
1. Create a Resource in Twingate and add some port restrictions (e.g. 443, 8080-8090)
2. Create a terraform resource representing it, for example:
```resource "twingate_resource" "TestResource" {
  name = "TestResource"
  address = "ipinfo.io"
  remote_network_id = ...
  group_ids = [...]
  protocols {
    allow_icmp = true
    tcp {
        policy = "RESTRICTED"
        ports = ["443", "8080-8090"]
    }
    udp {
        policy = "RESTRICTED"
        ports = ["443", "8080-8090"]
    }
  }
}
```
3. Run terraform import with the id of the resource, as an example:
`terraform import twingate_resource.TestResource UmVzb3VyY2U6MjE4MzI0MA==`
4. Now run `terraform plan` and observe that Terraform will highlight the protocols for change. This is because the tfState file does not contain any values in `protocols` .

**Comment by vmanilo** [comment]
thank you, can reproduce it

@alexmensch what do you think to which stage this bug should go?
