### ISSUE TITLE
updating location in `twingate_remote_network` fails

### ISSUE THREAD

**Issue by tjstansell** [Twingate/terraform-provider-twingate#239]
I happened to pick up the latest v0.2.2 release tonight and it saw that i had manually changed a location in the UI for a remote network.  It wanted to revert it.
```
  # module.remote_network["aws_euw2"].twingate_remote_network.this will be updated in-place
  ~ resource "twingate_remote_network" "this" {
        id       = "UmVtb3RlTmV0d29yazoxODgzMQ=="
      ~ location = "AWS" -> "OTHER"
        name     = "aws-euw2"
    }
```

However, the apply failed with:

```
module.remote_network["aws_euw2"].twingate_remote_network.this: Modifying... [id=UmVtb3RlTmV0d29yazoxODgzMQ==]
╷
│ Error: failed to update remote network with id UmVtb3RlTmV0d29yazoxODgzMQ==: A Remote Network with this name already exists.
│
│   with module.remote_network["aws_euw2"].twingate_remote_network.this,
│   on ../../modules/remote_network/main.tf line 18, in resource "twingate_remote_network" "this":
│   18: resource "twingate_remote_network" "this" {
│
╵
```

I reverted back to v0.2.1 so it didn't see the location field at all and was able to apply my other changes.

**Comment by alexmensch** [comment]
Thanks @tjstansell -- we're working on fixing this now

**Comment by vmanilo** [comment]
@tjstansell once we release new fixed version, you could update your terraform file like this to prevent change of `location` property (by default `location` set as OTHER, and when it's missing in terraform file provider tries to apply default value)

```
resource "twingate_remote_network" "this" {
       location = "AWS"
       name     = "aws-euw2"
}
```

**Comment by tjstansell** [comment]
Thanks. Yeah. Once this is working I'll be setting all my networks to "AWS". Btw, there were no changelogs in the last release. Think that could get amended to show the addition of this attribute?
