### ISSUE TITLE
Deprecate the `group_ids` argument in the `twingate_resource` resource

### ISSUE THREAD

**Issue by alexmensch** [Twingate/terraform-provider-twingate#242]
Issue #241 creates a new resource for access assignment, which conflicts with the existing group assignment functionality in the `twingate_resource` resource. We'll deprecate this functionality and remove it entirely at a later date in #225.

**Comment by alexmensch** [comment]
Re-opening this to align with our release planning.

**Comment by vmanilo** [comment]
@alexmensch this changes already in the main branch 

https://github.com/Twingate/terraform-provider-twingate/blob/main/twingate/internal/provider/resource/resource.go#L120

**Comment by alexmensch** [comment]
Ah, thanks! Closing
