### ISSUE TITLE
Create a new `access` block in `twingate_resource` for group and service account assignment

### ISSUE THREAD

**Issue by alexmensch** [Twingate/terraform-provider-twingate#245]
**Modified functionality**

Arguments

- (Optional) `access` block to define which groups and service accounts have access to the Twingate resource.
    - (Optional) `group_ids` of type `list(string)`
        - List of resource `id`s obtained from the `twingate_group` or `twingate_groups` data sources.
    - (Optional) `service_account_ids` of type `list(string)`
        - List of resource `id`s from service account resources
- (Optional) `authoritative` of type `boolean`
    - Default: `true`

Behavior

- We are deprecating the `group_ids` argument outside of the new `access` block in #242, which means that we must generate a blocking error if both `group_ids` and `access` are specified. Only one is allowed as they are mutually exclusive options after this change.
- Although both `group_ids` and `service_account_ids` are individually optional, at least one must be specified for the `access` block to be valid.
- The `authoritative` argument determines whether changes made outside of Terraform are overridden by Terraform. By default, Terraform is the authoritative source of true. When set to `false`, changes made outside Terraform are ignored.
- Only a single access block is allowed.

Example usage

```terraform
data "twingate_groups" "devops" {
  name = "DevOps"
}

resource "twingate_service_account" "github_actions_prod" {
  name = "Github Actions PROD"
}

resource "twingate_remote_network" "aws" {
  name = "AWS"
}

resource "twingate_resource" "internal_resources" {
  name = "All internal resources"
  address = "*.internal.int"
  remote_network_id = twingate_remote_network.aws.id
  protocols {
    allow_icmp = true
    tcp  {
      policy = "RESTRICTED"
      ports = ["80", "82-83"]
    }
    udp {
      policy = "ALLOW_ALL"
    }
  }
  access {
    service_account_ids = toset([twingate_service_account.github_actions_prod.id])
    group_ids = toset([data.twingate_groups.devops.id])
  }
  authoritative = false
}
```

**Comment by ekampf** [comment]
Yes lets enforce a single one for now...

**Comment by alexmensch** [comment]
Done

**Comment by alexmensch** [comment]
Making one more change to the spec here. Discussed with @ekampf and @vmanilo today.

1. We're pulling the `authoritative` argument outside of the individual `access` block.
- The rationale for this is that although there is no use case for having multiple `access` blocks today, we are currently working on making changes to our core policy framework that will allow assigning policies to individual access assignments. Once this is available in the core product we will:
  - Allow assigning a single policy ID to a specific access block. (Today this policy assignment is attached to the group.)
  - Check whether there are conflicting assignments between multiple access blocks (eg. The same group or user ID is assigned to the resource in different access blocks), and if so, generate an error on plan/apply.

2. The general pattern we will use in the future for relationships will be consistent with the above.
- We will decide which (Terraform) resource is the definitive one for the relationship. For example, in this case the `twingate_resource` is the definitive one for relationships with other entities: groups are added to and defined in resources, not the other way around.
- The `authoritative` flag will apply to the definitive resource.
- For example, if we create a new "group of resources" entity, we would decide that the group of resources is definitive: resources would be defined on the group of resources, and the group of resources will determine whether assignments are authoritative or not.
