### ISSUE TITLE
Add `service_account_ids` argument for `twingate_resource`

### ISSUE THREAD

**Issue by mllnd** [Twingate/terraform-provider-twingate#252]
Right now the `twingate_resource` resource only accepts a `group_ids` argument for defining the access to the instance. It would be quite convenient if the resource also accepted an additional argument, e.g. `service_account_ids`, which would allow users to define access for any service accounts.

In our use-case, it would remove the need to manually allow the service user for each of the newly added resources.

**Comment by mllnd** [comment]
Ah, just realised that #245 tackles that...

**Comment by alexmensch** [comment]
> Ah, just realised that #245 tackles that...

Yes, that's right @mllnd -- we're in the middle of work on that issue so it shouldn't be too long before we have a new release with that functionality. I'll close this, and you can follow #245 for updates.
