### ISSUE TITLE
`twingate_resource` visibility flags produce incorrect plan output

### ISSUE THREAD

**Issue by tjstansell** [Twingate/terraform-provider-twingate#258]
```
Terraform v1.3.7
on linux_arm64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.50.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/twingate/twingate v0.2.4
```

Create a new resource using the following:
```hcl
resource "twingate_resource" "test" {
    address           = "testing"
    group_ids         = [ "..." ]
    name              = "testing"
    remote_network_id = "..."

    protocols {
        allow_icmp = true
        tcp {
            policy = "ALLOW_ALL"
            ports  = []
        }
        udp {
            policy = "ALLOW_ALL"
            ports  = []
        }
    }
}
```
results in the following plan output.
```  
# twingate_resource.test will be created
  + resource "twingate_resource" "test" {
      + address           = "testing"
      + group_ids         = [
          + "...",
        ]
      + id                = (known after apply)
      + name              = "testing"
      + remote_network_id = "..."

      + protocols {
          + allow_icmp = true

          + tcp {
              + policy = "ALLOW_ALL"
              + ports  = []
            }

          + udp {
              + policy = "ALLOW_ALL"
              + ports  = []
            }
        }
    }
...
twingate_resource.test: Creating...
twingate_resource.test: Creation complete after 1s [id=UmVzb3VyY2U6MjIwODc1Mg==]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Then update it with the following settings:
```hcl
    is_browser_shortcut_enabled = false
    is_visible                  = false
```

and perform another plan and no changes are detected:
```
No changes. Your infrastructure matches the configuration.
```

change those settings to `true` and run another plan:
```
  # twingate_resource.test will be updated in-place
  ~ resource "twingate_resource" "test" {
        id                          = "UmVzb3VyY2U6MjIwODc1Mg=="
      + is_browser_shortcut_enabled = true
      + is_visible                  = true
        name                        = "testing"
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

In reality, though, the default value is `true` on the Twingate API.  The plan output in both cases are wrong.  When set to `false` it actually does nothing and doesn't track the setting.  When set to `true`, it doesn't detect the existing settings are already `true`.

I would expect that the new provider update would start pulling the values from the API and recording them in the state file regardless of if they are set in the resource.  Only then could it tell if a change has occurrs.  I would expect it to ignore the existing fields if they're not explicitly set in the resource to `true` or `false`.

**Comment by tjstansell** [comment]
Additionally, if I actually apply the resource while both settings are `true` then it does update and record the settings in the state file.  I can _then_ use `false` to disable them.  If I then comment out the settings (thereby no longer maintaining them) it seemed to keep the existing values in the state file.  If I then manually enable visibility via the UI, so now the actual value is `true`, the state file still has `false` and the resource setting is commented out, another plan at that point will show
```
  # twingate_resource.test will be updated in-place
  ~ resource "twingate_resource" "test" {
        id                          = "UmVzb3VyY2U6MjIwODc1Mg=="
      - is_visible                  = true -> null
        name                        = "testing"
        # (4 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```
claiming that it wants to set it to `null` ... which isn't valid at all.  It should either not want to change anything or it should claim it is setting it to `true` or `false` only.

**Comment by ekampf** [comment]
@vmanilo it seems we're missing `Default` value for the 2 new properties?
Also probably missing some test cases that should have failed here.

 https://github.com/Twingate/terraform-provider-twingate/blob/main/twingate/internal/provider/resource/resource.go#L104

**Comment by tjstansell** [comment]
I don't think you want a default value to be forced on folks.  I think the idea was that if you don't specify these settings (hence their value in the resource is `nil`), then don't manage it.  Therefore, folks can feel free to edit via the UI or whatever and any existing settings folks have placed do not get changed.  It should only include these settings in diffs and such if they're explicitly set to `true` or `false` in the resource.

**Comment by tjstansell** [comment]
I think it needs to be both `Optional: true` and `Computed: true`... but my terraform provider fu is rusty.

**Comment by tjstansell** [comment]
And if it's `nil` in the resource, then you compute it and set it to whatever the current state is (no change).  Something like that.

**Comment by alexmensch** [comment]
> I don't think you want a default value to be forced on folks. I think the idea was that if you don't specify these settings (hence their value in the resource is `nil`), then don't manage it. Therefore, folks can feel free to edit via the UI or whatever and any existing settings folks have placed do not get changed. It should only include these settings in diffs and such if they're explicitly set to `true` or `false` in the resource.

The other thing to keep in mind @ekampf is that we already have some kind of logic on the controller side to set these values to true or false under various conditions, so it probably is actually more appropriate to simply have these as override values to whatever the controller decides rather than default values.

**Comment by vmanilo** [comment]
@tjstansell thank you for reporting the issue, opened PR to fix it

**Comment by tjstansell** [comment]
Release 0.2.5 appears here in github, but not on the registry at https://registry.terraform.io/providers/Twingate/twingate/latest ... is there a delay getting that updated?

**Comment by ekampf** [comment]
@tjstansell this seems like an issue on Terraform side thats probably related to this: https://support.hashicorp.com/hc/en-us/articles/11239867821203-Terraform-Registry-to-Change-CDN-Providers-on-Jan-18-2023

**Comment by vmanilo** [comment]
@tjstansell should be good now

**Comment by tjstansell** [comment]
Thanks!  Worked great, btw!  So much nicer now!
