### ISSUE TITLE
Finding resource IDs to import

### ISSUE THREAD

**Issue by wyardley** [Twingate/terraform-provider-twingate#265]
It would be really helpful if you could make it easier to find resource IDs.

For example, given the following:
```hcl
// This is what shows up as one of my "networks"
resource "twingate_remote_network" "foo" {
  name     = "foo"
  location = "GOOGLE_CLOUD"
}

resource "twingate_connector" "radiant_bullfrog" {
  name = "radiant-bullfrog"
 remote_network_id = twingate_remote_network.foo.id
}
```

The graphql endpoint that the web console is using doesn't have networks or connectors, but rather `accessNodeCluster` and `accessNode` resources listed; If I try to import using either the IDs there, _or_ the literal resource name base64 encoded (as implied by the documentation), I get an error. I also don't see anything in the URL itself, or when editing the individual resources in the web console, that would give me a hint as to the correct ID terraform is looking for to import these resources.

```
% tf import twingate_connector.radiant_bullfrog cmFkaWFudC1idWxsZnJvZwo=
twingate_connector.radiant_bullfrog: Importing from ID "cmFkaWFudC1idWxsZnJvZwo="...
twingate_connector.radiant_bullfrog: Import prepared!
  Prepared twingate_connector for import
twingate_connector.radiant_bullfrog: Refreshing state... [id=cmFkaWFudC1idWxsZnJvZwo=]
│ Error: failed to read connector with id cmFkaWFudC1idWxsZnJvZwo=: {'id': ['Unable to parse global ID']}
```

If the IDs _are_ predictable or generated from the resource name, it would be really convenient if they could be imported via the friendly name only.

I found that using https://github.com/Twingate-Labs/Twingate-CLI will show me what I need pretty easily, but it would be helpful if you could improve your provider docs on getting resource IDs and / or make them easier to get from the web interface.

**Comment by alexmensch** [comment]
Hi @wyardley, thanks for the feedback! We do realize this is harder than it needs to be, so we will be making some changes here. The CLI can be used for now, as you point out, or by directly querying the GraphQL API.

The change we've internally committed to making is making the resource ID that's used/shown in the Admin Console consistent with the ID used in the API. This inconsistency has been causing the type of confusion and jumping through hoops that you describe, so we're going to fix that.

I don't have an exact timeline at this moment, but we just discussed this as a team, and the change will be scheduled within the next few sprints. I'll leave this issue open until we ship that change.

**Comment by vmanilo** [comment]
hey @wyardley do you still has issues with finding resource IDs?

I was checking that ids that you see in urls, should work with terraform as well 
alternatively you can use terraform datasources to get resource id

**Comment by wyardley** [comment]
The ones mentioned in the message above didn’t seem to show in the URL, but I’ve got things imported and know how to find the others.

datasources mostly require IDs too, no?

One other piece of feedback, which I can make a separate issue for if folks think it’s feasible: I don’t know if there’s precedent with other providers, but since I imagine providers _could_ fetch the human readable group name, plans would be a lot easier to read if they’d display the name vs the group vs the (decoded or not) ID

similarly, having the provider do the extra work to be able to import by human readable name vs ID would also be convenient.

**Comment by wyardley** [comment]
What I have sometimes done (tho still on the fence) is use the decoded vs encoded ID in the datasource. This creates an extra step when defining or changing it, but IMO looks a little prettier.
```hcl
data "twingate_group" "foo_bar" {
  id = base64encode("Group:73898")
}
```

**Comment by wyardley** [comment]
ps - I can see the ID in the URL now for groups. Pretty sure they didn't show up before.

**Comment by tjstansell** [comment]
FYI, we use the `twingate_groups` data source to list all active groups and then we can target groups by name.

**Comment by wyardley** [comment]
Ah, didn’t know that was a thing, but will give it a shot 👍 
Do they show up by name or ID in the plan then?

**Comment by wyardley** [comment]
@tjstansell curious how you're accessing it, given how it's structured. Following seems to work for me

```hcl
locals = {
  twingate_groups = {
    for g in data.twingate_groups.groups.groups : g["name"] => g["id"]
  }
}
// Reference e.g., local.twingate_groups["foo"]
```

Otherwise, seem to have to do something messy like `data.twingate_groups.groups.groups[index(data.twingate_groups.groups.groups.*.name,  "foo")].id,`?

**Comment by tjstansell** [comment]
We use this: 
```hcl
data "twingate_groups" "active" {
  is_active = true
}

locals {
  groups = { for v in data.twingate_groups.active.groups : v.name => v }
}
```
then elsewhere just reference with `local.groups[name].id`, etc...

**Comment by tjstansell** [comment]
We know we don't have overlapping group names, so not worried about that, even though, technically, Twingate allows groups to have identical names.

**Comment by wyardley** [comment]
Got it. that reads a little better. And yes, was wondering why it's a list not a set. identical names 😬
