### ISSUE TITLE
v0.3.0 shows changes when there should not be any

### ISSUE THREAD

**Issue by tjstansell** [Twingate/terraform-provider-twingate#276]
I attempted to update our deployment to the v0.3.0 release and move to the new `access {}` blocks.  It seems this should have been seen by the provider as a no-op.  During the transition period while you support both `group_ids = []` and `access { group_ids = [] }`, it seems that both should be populated by whatever the API returns.  If you specify one of these in your resource, it would effectively populate the other as well, I would think.

In our case, every resource shows the following proposed changes:
```
  # twingate_resource.this["my-resource"] will be updated in-place
  ~ resource "twingate_resource" "this" {
      ~ group_ids                   = [
          - "R3JvdXA6NzAwNDY=",
        ]
        id                          = "UmVzb3VyY2U6MjE5OTQ5Mg=="
      ~ is_authoritative            = false -> true
        name                        = "my-resource"
        # (4 unchanged attributes hidden)

      + access {
          + group_ids = [
              + "R3JvdXA6NzAwNDY=",
            ]
        }

        # (1 unchanged block hidden)
    }
```

The fact that `is_authoritative` is a new field, I would have expected it to show `null -> true` since it wasn't there before or not show a change at all since the default of `true` is effectively what was in place with just `group_ids` (before `access {}` was supported).  This is effectively just a transitionary "change".  If I show what's in the state file, it then shows the values have moved from one group_ids field to the other, which seems a little odd to me.

```hcl
$ terraform state show 'twingate_resource.this["my-resource"]'
# twingate_resource.this["my-resource"]:
resource "twingate_resource" "this" {
    address                     = "my-resource"
    group_ids                   = []
    id                          = "UmVzb3VyY2U6MjE5OTQ5Mg=="
    is_authoritative            = true
    is_browser_shortcut_enabled = true
    is_visible                  = false
    name                        = "my-resource"
    remote_network_id           = "UmVtb3RlTmV0d29yazoxODA0MA=="

    access {
        group_ids = [
            "R3JvdXA6NzAwNDY=",
        ]
    }
    ...
```

I'm reporting this because I didn't necessarily _expect_ there to be any changes when in reality all that's happening is re-organizing how the data is stored in terraform.  It has nothing to do with how the resource is configured.  I think your transition could be done better.

Feel free to tell me this is how it is expected to be and we can close this. :)

**Comment by ekampf** [comment]
Hey @tjstansell ,
 `is_authoritative` is a new and required field with default value `True` so that change is expected.
 Furthermore the `group_ids` field is deprecated and we expect the `access` block to be used in the future so as part of that change we migrated the state to the new field.

**Comment by tjstansell** [comment]
My main point was just that `group_ids` and `access { group_ids }` are, in theory, identical attributes of the resource. When terraform refreshes the existing resource, I would have expected it to populate both and then not seen any changes had been made.  That's what I expected to happen.  Not sure if I'm the only terraform user who would expect this.  Ideally version upgrades shouldn't incur unnecessary "changes" when, in fact, nothing is changing on the resource.  I think that if both of these fields were "computed" fields and refreshed, then as folks update to v0.3.0, they'd see both populated with the same values.  I would have expected to see the current state represented by:
```hcl
resource "twingate_resource" "this" {
    address                     = "my-resource"
    group_ids = [
        "R3JvdXA6NzAwNDY=",
    ]
    id                          = "UmVzb3VyY2U6MjE5OTQ5Mg=="
    is_authoritative            = true
    is_browser_shortcut_enabled = true
    is_visible                  = false
    name                        = "my-resource"
    remote_network_id           = "UmVtb3RlTmV0d29yazoxODA0MA=="

    access {
        group_ids = [
            "R3JvdXA6NzAwNDY=",
        ]
    }
```
Anyway, not a big deal,  but when you update to a new version of a provider and it then says it's going to change all your resources, that can be alarming.  It also makes it hard to see if it really is going to change a value instead of just change how it stores that value in the state store.

Feel free to close this.
