### ISSUE TITLE
Support for `Alias` for `twingate_resource`

### ISSUE THREAD

**Issue by jimsmith** [Twingate/terraform-provider-twingate#315]
Hi new user, on the 14 day trial..

There does not seem any mention of support for `alias` for `twingate_resource` https://registry.terraform.io/providers/Twingate/twingate/latest/docs/resources/resource

There is nothing in the codebase in this repo that has this as well.

I need this for setting **Alias** as it's a configuration that I can do in your portal:
![image](https://user-images.githubusercontent.com/2676701/231423548-f7352e68-086e-483a-8c69-d46d579fe04e.png)

```
│ Error: Unsupported argument
│ 
│   on main.tf line 52, in resource "twingate_resource" "resource":
│   52:   alias ="db.test"
│ 
│ An argument named "alias" is not expected here.
```

```
Terraform v1.4.4
on darwin_arm64
+ provider registry.terraform.io/twingate/twingate v1.0.0-rc1
```

**Comment by alexmensch** [comment]
Hi @jimsmith thanks for creating this issue -- we are working on adding this currently, and we'll get a new provider release out as soon as we can! Continue to watch this issue for updates.

**Comment by jimsmith** [comment]
Hi @alexmensch  thanks for that, looking forward to this as doing an out of band update in the UI defeats the purpose for myself and devops folk.

Also if I can ask after the trial will terraform still work as I noticed in your documentation it says Enterprise plan is needed that can't be right surely as that restricts engineers and developers from using terraform given its an open source tool doesn't seem right its behind a pay wall?

https://www.twingate.com/docs/terraform-getting-started

**Comment by jimsmith** [comment]
![Screenshot_20230412_201828_Firefox](https://user-images.githubusercontent.com/2676701/231564668-17266903-bc98-4e3a-b0fd-6452a2999534.jpg)

**Comment by alexmensch** [comment]
> Hi @alexmensch thanks for that, looking forward to this as doing an out of band update in the UI defeats the purpose for myself and devops folk.
> 
> Also if I can ask after the trial will terraform still work as I noticed in your documentation it says Enterprise plan is needed that can't be right surely as that restricts engineers and developers from using terraform given its an open source tool doesn't seem right its behind a pay wall?
> 
> https://www.twingate.com/docs/terraform-getting-started
> 
> The trial account is Business plan but it maybe Teams plan that we go with although it was Teams trial that was selected on sign up.

@jimsmith thanks for pointing that out! That's an out of date reference, and I put in a change in the docs that will be reflected live soon. We allow API access (and hence Terraform support) for all of our tiers per our [pricing page](https://www.twingate.com/pricing), so Terraform will work for you on any tier.

In the meantime, the alias parameter will be available in the next provider release, which we'll aim to do soon.

**Comment by alexmensch** [comment]
Hi @jimsmith just in case you haven't already seen it, we do have a pre-release out as `v1.0.0-rc2` that you can use now. Just be aware that there is one breaking change from the prior `v0` major version that's detailed in the [release notes](https://github.com/Twingate/terraform-provider-twingate/releases/tag/v1.0.0-rc2).

We're going to do a full public release of `v1.0.0` early next week!

**Comment by jimsmith** [comment]
Hi @alexmensch thanks for this so `1.0.0-rc2` terraform's registry comes back 404 on this:

```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 4.61.0"...
- Finding twingate/twingate versions matching "1.0.0-rc2"...
- Installing hashicorp/aws v4.61.0...
- Installed hashicorp/aws v4.61.0 (signed by HashiCorp)
╷
│ Error: Failed to install provider
│ 
│ Error while installing twingate/twingate v1.0.0-rc2: could not query provider registry for registry.terraform.io/twingate/twingate: failed to retrieve authentication checksums for provider: 404 Not Found
│ returned from github.com
╵

```

`1.0.0-rc1` is still there and found: 

```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding twingate/twingate versions matching "1.0.0-rc1"...
- Finding hashicorp/aws versions matching "~> 4.61.0"...
- Installing twingate/twingate v1.0.0-rc1...
- Installed twingate/twingate v1.0.0-rc1 (self-signed, key ID E8EBBE80BA0C9369)
- Installing hashicorp/aws v4.61.0...
- Installed hashicorp/aws v4.61.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by ekampf** [comment]
Hey @jimsmith @jkrall - There's was some syncing issue with Terraform Registry so we released `rc2` but it wasnt updated on their end.
In any case its fixed now AND we've also just released `v1.0.0` with this change so you can just as well upgrade to that.

**Comment by jkrall** [comment]
Excellent, thanks!

**Comment by jimsmith** [comment]
Great, thanks, using `v1.0.0` and `alias` is working 👍
