### ISSUE TITLE
Some changes in the protocols block for the resource twingate_resource does not trigger a change in Terraform

### ISSUE THREAD

**Issue by twingate-blee** [Twingate/terraform-provider-twingate#351]
With this example resource
```
resource "twingate_resource" "resource" {
  name = "network"
  address = "internal.int"
  remote_network_id = twingate_remote_network.aws_network.id

  protocols {
    allow_icmp = true
    tcp  {
      policy = "RESTRICTED"
      ports = ["80", "82-83"]
    }
    udp {
      policy = "ALLOW_ALL"
    }
  }

  access {
    group_ids = [twingate_group.aws.id]
    service_account_ids = [twingate_service_account.github_actions_prod.id]
  }
}
```

Terraform ignores some policy changes. For example:

DENY_ALL -> RESTRICTED
DENY_ALL -> ALLOW_ALL
RESTRICTED -> DENY_ALL
RESTRICTED -> ALLOW_ALL (with ports, should prompt message that port is not needed)
Removing the protocols block does not trigger a change
Removing ports when the policy is set to "RESTRICTED"

These changes do work:

~ policy = "ALLOW_ALL" -> "RESTRICTED"
~ policy = "ALLOW_ALL" -> "DENY_ALL"
~ policy = "RESTRICTED" -> "ALLOW_ALL" (if you remove the ports)

I also found that when a policy is set as RESTRICTED but you don't give it any ports it treats it as a DENY_ALL

Another strange thing is when I create a new resource starting with 
```
policy = "DENY_ALL"
```

Then update it to
```
policy = "ALLOW_ALL"
```

The Terraform plan shows
```
  # module.twingate.twingate_resource.resource will be updated in-place
  ~ resource "twingate_resource" "resource" {
        id                          = "UmVzb3VyY2U6MjI3NjAzNA=="
        name                        = "test"
        # (5 unchanged attributes hidden)

      ~ protocols {
            # (1 unchanged attribute hidden)

          ~ udp {
              ~ policy = "RESTRICTED" -> "ALLOW_ALL"
                # (1 unchanged attribute hidden)
            }

            # (1 unchanged block hidden)
        }
    }
```
The TF plan should be "DENY_ALL" -> "ALLOW_ALL" but it is showing as "RESTRICTED" -> "ALLOW_ALL". Maybe it is because of this https://github.com/Twingate/terraform-provider-twingate/blob/0e03be7bf944b00e6a5f86b4ec366661ab498ea1/twingate/internal/model/resource.go#L159-L160

**Workaround**

Change the policy to ALLOW_ALL then apply. Then you can change it to DENY_ALL and apply

**Comment by ekampf** [comment]
Re-opening issue as we've had to revert the above PRs
