### ISSUE TITLE
Feature Request: Ability to Add Groups/Service Accounts to Existing Resources in Terraform

### ISSUE THREAD

**Issue by TylerStaplerAtFanatics** [Twingate/terraform-provider-twingate#357]
## Description:
We currently have a setup where we create resources using one Terraform stack, but would like to manage access to those resources in separate Terraform stacks. However, the current Terraform provider for Twingate doesn't seem to support adding groups or service accounts to existing resources. We'd like to request a feature that allows for this sort of configuration.

## Use case:
In our setup, we have one Terraform stack which creates the resources, and different stacks that are responsible for managing group and service account permissions for those resources. We want to be able to grant individual groups and service accounts permission to access the resources, without having to include the full resource configuration in each stack. This would allow us to separate our infrastructure management (i.e., the resources themselves) from our access management (i.e., who or what can access those resources), providing a clearer separation of concerns and making our setup more manageable.

This makes it easier for our Security team to review who/what has access to a resource if we have one resource per host/domain rather than multiple resources.

## Potential solution:
Add a new Terraform resource or extend an existing one to allow adding groups or service accounts to existing resources. This resource should take the ID of the existing resource, as well as the IDs of the groups or service accounts to add, and it should modify the existing resource rather than creating a new one.

Thank you for considering this feature request. Please let us know if there's any additional information we can provide.

**Comment by alexb-twingate** [comment]
Hi @TylerStaplerAtFanatics - we aren't currently planning to build this at the moment. There are a few reasons why, including:
- Our API currently isn't designed for this flow to be optimized well. All accesses are keyed on a Resource, it's challenging to build the provider to easily look up whether an access is present.
- I don't think there's a great way to manage the same Resources in two places. Specifically, if you have a second configuration for managing Resource access, there's not an easy way to pull in Resources IDs to use to manage the access. I'd love to learn more about how you plan to do that, whether it's using outputs or a data source.

For now, this isn't a use case that we're going to be able to support. I'd love to learn more about your needs so we could potentially support it in the future.
