### ISSUE TITLE
Add support for setting expiration dates on `twingate_service_account_key` resource

### ISSUE THREAD

**Issue by alexb-twingate** [Twingate/terraform-provider-twingate#390]
**Modified functionality**

Arguments

- (Optional) `expiration_times` specifies how many days until a Service Account Key expires. This should be an integer between 0 and 365 representing the number of days until the Service Account Key will expire.
  - Defaults to 0, meaning the key will never expire.

Behavior

- `expiration_time` determines when the service account key will expire. This is set during the initial run of the plan when the service account key is first created.
  - This value is an integer between 0 and 365. Values outside of this range should return the same error that the API does: "Invalid key expiration time. A value from 0-365 is required."
  - An `expiration_time` of 0 means the key never expires.
  - If no value is passed to `expiration_time`, it defaults to 0.
- On subsequent runs after the key has been created:
  - If the service account key no longer exists, it will be re-created with the provided expiration time starting from the re-creation date.
  - If the service key still exists, it will not be re-created even if expired or revoked.

Example usage

```terraform
resource "twingate_service_account" "github_actions_prod" {
  name = "Github Actions Prod"
}

resource "twingate_service_account_key" "github_key" {
  name = "Github Actions Prod Key"
  service_account_id = twingate_service_account.github_actions_prod.id

  expiration_time = 27
}
```

This key will not be recreated when it expires or if it is revoked.

To automatically rotate the key using  `time_rotating` from the [time](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/rotating) provider:
```terraform
resource "time_rotating" "key_rotation" {
  rotation_days = 30
}
resource "time_static" "key_rotation" {
  rfc3339 = time_rotating.key_rotation.rfc3339
}

resource "twingate_service_account_key" "github_key" {
  name = "Github Actions Prod Key"
  service_account_id = twingate_service_account.github_actions_prod.id

  expiration_time = time_rotating.key_rotation.rotation_days

  lifecycle {
    replace_triggered_by = [time_static.key_rotation.rfc3339]
}
```

**Comment by tjstansell** [comment]
A couple of suggestions regarding this proposal:
- `expiration_time` implies to me that it expects a static timestamp.  I wish it was called `expire_in_days` or something similar to imply that it's calculated using a number of days.  I get that it's named after the `expirationTime` API argument, which itself is poorly named.  Just throwing this out there.
- defining the expiration time for your key should not force any specific behavior on when that key gets deleted or recreated.  We should be able to control that behavior explicitly via a new attribute (e.g. like [`triggers_replace`](https://developer.hashicorp.com/terraform/language/resources/terraform-data#triggers_replace) in the `terraform_data` resource) or via the `replace_triggered_by` attribute in a `lifecycle {}` block.

**Comment by tjstansell** [comment]
Personally, I'd love it if we could do something like this:
https://github.com/tjstansell/terraform-key-rotator/blob/main/twingate-triggers/main.tf#L6-L13

**Comment by alexb-twingate** [comment]
Took another pass at this, and here's what we're thinking:
- We won't rotate the key automatically. If the key is expired or revoked, running Terraform again will not recreate the key.
- You can rotate your keys by using a `lifecycle` block with a `replace_triggered_by` item pointing to either the key's state (i.e. whether it's been revoked or expired) or by pointing it at a `time_rotating` Resource to regularly rotate it.

I think this is similar to the other example in the repo that you've shared and should hopefully make it easier and more explicit to control key lifecycle.

**Comment by vmanilo** [comment]
> On subsequent runs after the key has been created:
> * If the service key still exists, it will not be re-created even if expired or revoked.

just to be sure, this will change current behaviour, are you ok with that?

**Comment by vmanilo** [comment]
> To make it easier to rotate keys, we should also expose the state

I've tried to test such scenario, but terraform doesn't allow cyclic dependencies, we can't refer to object itself

```
resource "twingate_service_account" "test" {
  name = "Test account"
}

resource "twingate_service_account_key" "test_key" {
  name = "Test key"
  service_account_id = twingate_service_account.test.id

  lifecycle {
    replace_triggered_by = [twingate_service_account_key.test_key.status]
  }
}
```

**Comment by tjstansell** [comment]
I suppose that makes sense... `replace_triggered_by` is intended to handle side affects between resources.  Does it make sense to introduce a new attribute that helps control this internally, like
```hcl
 resource "twingate_service_account_key" "test_key" {
  name = "Test key"

  service_account_id = twingate_service_account.test.id
  replace_when       = ["EXPIRED", "REVOKED"]
}
```
(where it would default to `[]`)

The utility of `is_active` goes away if you expose the raw `status` attribute.

**Comment by alexb-twingate** [comment]
I've removed that as example since you're right that it's between resources.

For now, we won't add a `replace_when` attribute and we'll keep `is_active` and won't replace it with `status` (since neither is needed). Our thinking is that generally keys will be regularly rotated and we can leave that rotation up to you for now.

If this presents a problem down the line, we can add the `replace_when` attribute or one that does similar things.
