### ISSUE TITLE
Creating twingate_resource is failing with Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by PawelToporBitpanda** [Twingate/terraform-provider-twingate#403]
For 1 week terraform with Twingate provider is failing when creating twingate_resource. It returns the following error:

```
Error: failed to create resource: Message: Post "https://org.twingate.com/api/graphql/": POST https://org.twingate.com/api/graphql/ giving up after 11 attempt(s): Post "https://org.twingate.com/api/graphql/": net/http: request canceled (Client.Timeout exceeded while awaiting headers), Locations: [], Extensions: map[code:request_error]
```
But as a result, the resource in Twingate is created 11 times so I assume that the provider cannot retrieve the creation status.

Terraform version: 1.5.6
Provider version: 1.2.1 and 1.1.2

Plan:
```
{
  address :"xxx.xxx.xxx"
  id :Known after apply
  is_authoritative : Known after apply
  is_browser_shortcut_enabled : Known after apply
  is_visible : Known after apply
  name : "name"
  remote_network_id : "xxxxxxxxxxxxxxxxxxxxxxx"
  access {
    group_ids :
    [
      "R3xxxxxx"
      "R3xxxxxxx"
      "R3xxxxx"
      "R3xxxxxx"
      "R3xxxxxx"
    ]
  }
}
```
Expected behavior:
Terraform provider successfully represents the created resource

Update: Increasing timeout using TWINGATE_HTTP_TIMEOUT env variable to 30s solved the issue

**Comment by ekampf** [comment]
@PawelToporBitpanda out default timeout value is `10s` (you can try overriding it by setting `TWINGATE_HTTP_TIMEOUT` env var to a higher integer.
But `10s` seems like a lot - any idea why it would take that long?   It this running. on a remote machine with poor network?  or any chance you have the same resource being updated from two places within the code in parallel causing a DB lock?

Can you share some code snippets and\or logs?

**Comment by PawelToporBitpanda** [comment]
Thanks for the answer, looks like increasing the timeout to 30s solved the issue. (Did two attempts this morning with default 10s timeout - it failed again and with 30s timeout - it worked).

I will leave here some context anyway as you may be interested:
We are using Terraform Cloud with self-hosted terraform runners on AWS ECS with direct internet gateway access. So networking there should not be any bottlenecks. We have also one central workspace that maintains all the Twingate configurations so there is no chance that the resource is managed from two places at the same time. Also in the last attempts I was using `-target` to make sure that I was only deploying one resource.

In the attachment, you can find the logs with the debug flag

Thanks anyway for the help as increasing timeout unblocked us
[logs.txt](https://github.com/Twingate/terraform-provider-twingate/files/12735733/logs.txt)
