### ISSUE TITLE
Add support for filtering for twingate_users data source

### ISSUE THREAD

**Issue by twingate-blee** [Twingate/terraform-provider-twingate#437]
**Modified functionality**

Only one of email, email_regex, email_contains, email_exclude, email_prefix or email_suffix must be set.

- (Optional) `email` of type `string`
  - Returns only users that exactly match this email.
 
- (Optional) `email_regex` of type `string`
  - The regular expression match of the email of the user.

- (Optional) `email_contains` of type `string`
  - Match when the value exist in the email of the user.

- (Optional) `email_exclude` of type `string`
  - Match when the value does not exist in the email of the user.
 
- (Optional) `email_prefix` of type `string`
  - The email of the user must start with the value.

- (Optional) `email_suffix` of type `string`
  - The email of the user must end with the value.

Only one of first_name, first_name_regex, first_name_contains, first_name_exclude, first_name_prefix or first_name_suffix must be set.

- (Optional) `first_name` of type `string`
  - Returns only users that exactly match the first name.
 
- (Optional) `first_name_regex` of type `string`
  - The regular expression match of the first name of the user.

- (Optional) `first_name_contains` of type `string`
  - Match when the value exist in the first name of the user.

- (Optional) `first_name_exclude` of type `string`
  - Match when the value does not exist in the first name of the user.
 
- (Optional) `first_name_prefix` of type `string`
  - The first name of the user must start with the value.

- (Optional) `first_name_suffix` of type `string`
  - The first name of the user must end with the value.

Only one of last_name, last_name_regex, last_name_contains, last_name_exclude, last_name_prefix or last_name_suffix must be set.

- (Optional) `last_name` of type `string`
  - Returns only users that exactly match the last name.
 
- (Optional) `last_name_regex` of type `string`
  - The regular expression match of the last name of the user.

- (Optional) `last_name_contains` of type `string`
  - Match when the value exist in the last name of the user.

- (Optional) `last_name_exclude` of type `string`
  - Match when the value does not exist in the last name of the user.
 
- (Optional) `last_name_prefix` of type `string`
  - The last name of the user must start with the value.

- (Optional) `last_name_suffix` of type `string`
  - The last name of the user must end with the value.

- (Optional) `roles` of type `[string]`
  - Returns users that match a list of roles. valid roles : `ADMIN `, `DEVOPS `, `SUPPORT `, `MEMBER`.
      
**Behavior**

- Current behavior returns all users. This will allow filtering based on the criteria above

**Example usage**

```terraform
data "twingate_users" "filter" 
{
  email_suffix = "twingate.com"
  roles  = ["ADMIN"] 
}
```

**Comment by tjstansell** [comment]
This seems overly complex to maintain and I would argue makes it harder for folks to write dynamic terraform.  You sure you don't want to just support multiple filters like other providers by providing a `filter {}` block, like:
```hcl
data "twingate_users" "filtered" {
  filter {
    field  = "email"
    op     = "endsWith"
    values = ["@twingate.com", "@partner.com"]
  }
  filter {
    field  = "email"
    op     = "contains"
    values = ["fred"]
  }
}
```
which would then equate to a pseudo-expression like:

`(email endsWith twingate.com OR email endsWith partner.com) AND (email contains fred)`

I'm not sure if your graphQL API even supports that, but adding a separate argument for every field and operator combination you support seems very odd and not very scalable.

Additionally, is there a distinction between which filtering would happen server-side via the API and which might happen locally?  In your example, you filter by both email and roles, but the API looks like it only supports filtering by `email` field right now.

**Comment by vmanilo** [comment]
The idea was to make it less verbose, and for more complex cases use regexp

```terraform
data "twingate_users" "filtered" {
  email_regex = "^.*fred.*(twingate\.com|partner\.com)$"
}
```

**Comment by tjstansell** [comment]
Yeah.  Your method is certainly more compact for the general use-case where you have simple filtering needs.  Anything more complex is likely to be done via terraform after the fact anyway using all of the attributes available instead of just the ones the API allows you to filter on.

**Comment by vmanilo** [comment]
Do you facing more complex scenarios in practice?

**Comment by tjstansell** [comment]
In practice, we don't even use these data sources, aside from `twingate_groups` to find all of the `SYNCED` groups from Okta.  But even with that, we just pull all groups and filter ourselves locally with terraform.  I'd do whatever I needed to make as few API calls as possible, essentially.  I was just thinking about how others might want to and the overall use of the provider.  Most of the plural data sources only have the name field to match on, so something like this is easy.  If you start to support lots of attributes to filter on then things start to get a little unmanageable.  Having a consistent filtering mechanism that you can build AND/OR-like expressions with just feels cleaner.  Is it necessary?  Probably not.   My brain just sets of alarms when I see repetitive patterns like this as they don't feel right.  In reality, anything complex I'd probably do via terraform anyway because I likely want _multiple_ complex filters and it's just more efficient to hit the API once and pull everything rather than hitting the API for each filter group.

**Comment by ekampf** [comment]
I think when you define multiple filters in a datasource its an AND
if you want to do OR you can define multiple datasources with different filters and read from both of them in TF?
