### ISSUE TITLE
twingate_resource update failing to remove service_account

### ISSUE THREAD

**Issue by kaarla** [Twingate/terraform-provider-twingate#459]
I'm updating a twingate_resource, removing a service account access I don't need anymore, this is my code:

```
resource "twingate_resource" "snowflake" {
  name                        = "Snowflake"
  address                     = "[redacted]"
  remote_network_id           = data.twingate_remote_network.[redacted].id
  is_browser_shortcut_enabled = true

  protocols = {
    allow_icmp = true
    tcp = {
      policy = "ALLOW_ALL"
    }
    udp = {
      policy = "ALLOW_ALL"
    }
  }

  access {
    group_ids = [twingate_group.snowflake.id]
  }
}
``` 

The first time, the plan it showed correctly that the access would be removed:
```
update
access {
delete
service_account_ids :
[
delete
"[redacted]"
]
null
}
```

It successfully removed the access, but retrieves this error after applying:

```
Error: Provider produced inconsistent result after apply
When applying changes to twingate_resource.snowflake, provider "provider[\"registry.terraform.io/twingate/twingate\"]" produced an unexpected new value: .access[0].service_account_ids: was null, but now cty.SetVal([]cty.Value{cty.StringVal("[redacted]")}).

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

I tried running a new plan, but even now that the account access is not present anymore, plans to remove it again instead having an empty plan. I tried assigning back the service account manually and triggered a new plan but the result is the same.

**Comment by twingate-blee** [comment]
@kaarla Which version of the Twingate provider are you using? I think this is now fixed in v2.0.0 that was released last week

**Comment by kaarla** [comment]
@twingate-blee I was using `v2.0.0` implicitly, now I tried using it explicitly just in case, but the result is the same, when it plans still finds the service account that is not assigned anymore.

Code:
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
    twingate = {
      source = "twingate/twingate"
      version = "~> 2.0.0"
    }
  }
}
```

Plan:

![Screenshot 2024-01-24 at 11 56 03 a m](https://github.com/Twingate/terraform-provider-twingate/assets/29378995/4c3d5dd1-3eb8-4f93-adcb-21e591877661)

Infrastructure (Snowflake Access is a group, not a service account):

![Screenshot 2024-01-24 at 11 58 36 a m](https://github.com/Twingate/terraform-provider-twingate/assets/29378995/1f7210f7-0972-4b1c-adca-5b167c6214e9)

**Comment by twingate-blee** [comment]
@kaarla Thanks for reporting the bug. We found the issue and fixed it. A new version with the fix will be released soon.

**Comment by kaarla** [comment]
Thank you! Looking forward to use it.
