### ISSUE TITLE
Add support for verified serial numbers

### ISSUE THREAD

**Issue by alexb-twingate** [Twingate/terraform-provider-twingate#465]
**New functionality**
- Add a new resource `twingate_serial_number`.
- `twingate_serial_number` has the following attributes:
  - `serial_number` (String) The verified serial numbers for the Twingate account. 
- Add a new data source `twingate_serial_numbers`:
  - The data source itself has the following parameters:
    - `has_matched_devices` (Boolean) If `true`, only returns serial numbers with matching devices. If `false`, only returns serial numbers with no matching devices.
    - `serial_number` (String) returns only serial numbers that exactly match this serial number.
    - `serial_number_regex` (String) returns only serial numbers that fulfill this regex.
    - `serial_number_contains` (String) returns only serial numbers that contain this string.
    - `serial_number_exclude` (String) return only serial numbers that do not contain this string.
    - `serial_number_prefix` (String) return only serial numbers that start with this string.
    - `serial_number_suffix` (String) return only serial numbers that end with this string.
  - `twngate_serial_numbers` has the following read-only attributes:
    - `serial_numbers` (Set of String), a set of serial number objects
      - Each `serial_number` has the following attributes:
        - `id` (String) the `serial_number`'s ID
        - `matchedDevicesNum` (Int) the number of matched devices with this serial number
        - `serial_number` (String) the serial number itself

**Behavior**
- The `twingate_serial_numbers` resource is used to define verified serial numbers for the Twingate account. 
  - Serial numbers are added and removed via the `serialNumbersCreate` and `serialNumbersDelete` GraphQL mutations.
  - When authoritative, the list of serial numbers provided via Terraform should overwrite anything set via the Admin Console or other sources.
  - When not authoritative, the list of serial numbers provided via Terraform should ignore anything not set via Terraform.
- The `twingate_serial_numbers` resource is a singleton. If more than one `twingate_serial_numbers` resource is created, throw an error: "Only a single instance of `twingate_serial_numbers` may be used per account."
- The `twingate_serial_numbers` data source is used to query serial numbers that are part of the Twingate account.
  - Its behavior roughly matches the `serialNumbers` GraphQL query.

**Example usage**
```terraform
resource "twingate_serial_numbers" "serial_numbers" {
  serial_numbers = toset([
    "someSerialNumber",
    "anotherSerialNumber",
    "aThirdSerialNumber"
  ])
  is_authoritative = false
}

data "twingate_serial_numbers" "fetched_serial_numbers" {
  has_matched_devices = true
  serial_number_prefix = "apple"
}
```

**Comment by ekampf** [comment]
Since singleton isnt a good pattern for TF we need to change this to be single object per serial.
This, howveer, would result in TONS of GET API calls to controller which we want to avoid.
Need to check if the following process is possible:
1. Provider loads up, check if it has any "serial_number" resources defined
2. If yes: fetch ALL serials to memory
3. Validate resources exist against memory (instead of making a GET call per resource)

**Comment by ekampf** [comment]
I think the right solution here, instead of messing with singletons, is that each serial is its own resource
