### ISSUE TITLE
Add GPG keys to OpenTofu registry

### ISSUE THREAD

**Issue by joeybenamy** [Twingate/terraform-provider-twingate#479]
The registry for this provider does not have GPG keys so we are getting this warning on init:

> - Installing twingate/twingate v2.0.1...
> - Installed twingate/twingate v2.0.1. Signature validation was skipped due to the registry not containing GPG keys for this provider

Can you add GPG keys so we can benefit from signature validation?

**Comment by twingate-blee** [comment]
What version of terraform are you running? I'm trying to duplicate the issue but when I run init. I get:
```
- Installing twingate/twingate v2.0.1...
- Installed twingate/twingate v2.0.1 (self-signed, key ID E8EBBE80BA0C9369)
```

**Comment by joeybenamy** [comment]
> What version of terraform are you running? I'm trying to duplicate the issue but when I run init. I get:
> 
> ```
> - Installing twingate/twingate v2.0.1...
> - Installed twingate/twingate v2.0.1 (self-signed, key ID E8EBBE80BA0C9369)
> ```

Using OpenTofu 1.6.2

**Comment by twingate-blee** [comment]
Ok that make sense now. We will need to push to the OpenTofu Registry. Thanks

**Comment by joeybenamy** [comment]
> Ok that make sense now. We will need to push to the OpenTofu Registry. Thanks

You're welcome.  Sorry for not providing more context!

**Comment by bertekintw** [comment]
@joeybenamy 
Can you please try with our latest version (2.1.2) and let us know?
We are able to use Opentofu without signature warning ; we'd like to make sure it works for you too before we close the issue.
Thanks.

**Comment by joeybenamy** [comment]
> @joeybenamy Can you please try with our latest version (2.1.2) and let us know? We are able to use Opentofu without signature warning ; we'd like to make sure it works for you too before we close the issue. Thanks.

Thanks so much.  I can confirm it is working.
```
joey@ONCO-3400:~/source/terraform-workspace/vendors/twingate/aws$ tofu init

Initializing the backend...

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to OpenTofu
- Reusing previous version of hashicorp/aws from the dependency lock file
- Reusing previous version of twingate/twingate from the dependency lock file
- Using previously-installed hashicorp/aws v5.42.0
- Using previously-installed twingate/twingate v2.1.2

OpenTofu has been successfully initialized!
```
