### ISSUE TITLE
Add internet security and DNS filtering to terraform provider

### ISSUE THREAD

**Issue by observeinc-johnny** [Twingate/terraform-provider-twingate#504]
Hi folks,

Really enjoying the usage of the terraform provider for the rest of the configuration.

Requesting some DNS filtering and internet security configs to be controlled as well:

- allow the TF provider to add / remove from allowlist
- allow the TF provider to add / remove from the denylist
- allow the TF provider to toggle on / off any of the prebuilt categories

Thanks

**Comment by alexb-twingate** [comment]
This is now handled in #466
