### ISSUE TITLE
Invalid URL for migration guide

### ISSUE THREAD

**Issue by joeybenamy** [Twingate/terraform-provider-twingate#505]
The URL in the warning for 3.0.0 returns a 404.

> │ Warning: Please update the access blocks.
> │ 
> │   with twingate_resource.twingate_resource["FHIR Document Gateway"],
> │   on resources.tf line 1, in resource "twingate_resource" "twingate_resource":
> │    1: resource "twingate_resource" "twingate_resource" {
> │ 
> │ See the v2 to v3 migration guide in the Twingate Terraform Provider
> │ documentation
> │ https://registry.terraform.io/providers/Twingate/twingate/latest/docs/guides/migration-v2-to-v3-guide
> │ 
> │ (and 10 more similar warnings elsewhere)

![image](https://github.com/Twingate/terraform-provider-twingate/assets/88293693/37dc7842-4992-40dd-b1a3-85b122098aab)

**Comment by twingate-blee** [comment]
@joeybenamy Sorry about that. This is now fixed
