### ISSUE TITLE
Possibility to import users

### ISSUE THREAD

**Issue by Jorehn** [Twingate/terraform-provider-twingate#519]
We started with twingate, but are running in a sort of catch 22. We need a user to be able to create the account, but we also really would like to bring the users under terraform control. Unfortunately we aren't able to import the users in terraform, so it seems we have to leave 1 user out of terraform control. 

It would be a real nice addition for us to be able to import users

**Comment by alexb-twingate** [comment]
You should be able to import users into Terraform but (maybe this is what you're looking for) you won't be able to control things like their name, role or email. Could you share a little bit about your use case?

I think this may be outside of the scope of what we're able to do today. I worry this could be a little too chicken-and-eggy where you accidentally delete the user managing Terraform in Terraform and then lock yourselves out of Twingate.

**Comment by alexb-twingate** [comment]
What do you want to do once you've imported a user? What documentation are you looking at?

You should be able to use the [`twingate_user`](https://registry.terraform.io/providers/Twingate/twingate/latest/docs/data-sources/user) or the [`twingate_users`](https://registry.terraform.io/providers/Twingate/twingate/latest/docs/data-sources/users) to import one or more users. You can then create groups with those users using the [`twingate_group`](https://registry.terraform.io/providers/Twingate/twingate/latest/docs/resources/group) resource.

You aren't able to manage a user that was imported, e.g. you can't change their role or name.

**Comment by Jorehn** [comment]
I want to be able to modify the user, I can update the API token, so it shouldn't be dependant on one specific user? I misread it in the documentation. I thought I read it in the docs, the user import (in terraform) wasn't supported but it seems only to show once you actually try to import it.

**Comment by alexb-twingate** [comment]
I believe that the API token isn't dependent on a specific user. For example, if a user is deleted, the API key will remain valid. 

Have you been able to solve this on your end?

**Comment by alexb-twingate** [comment]
Going to mark this closed for now - feel free to comment or reopen.
