### ISSUE TITLE
Add data source: twingate_user

### ISSUE THREAD

**Issue by bertekintw** [Twingate/terraform-provider-twingate#61]
Arguments

- (Required) `id`
    - This ID can be obtained either directly from the public admin API or referenced via the `twingate_users` data source in our Provider.

Exported attributes

- `id` (String)
- `firstName` (String)
- `lastName` (String)
- `email` (String)
- `role` (String)

GraphQL

```graphql
query {
  user(id: "VXNlcjoxODc3NQ==")
   {
        id
        firstName
        lastName
        email
        role
  }
}
```

**Comment by alexmensch** [comment]
Updated with new `role` attribute
