### ISSUE TITLE
No way to pull the current group membership(s) in the datasources

### ISSUE THREAD

**Issue by Eforen** [Twingate/terraform-provider-twingate#610]
Looking through the data's there does not seem to be any way to get the memberships of a group.

**Comment by alexb-twingate** [comment]
Hi @Eforen - just curious, what are you planning to do with that list of users once you have them?

This is something that we can add, as our API does support this. However, there's not much you can do with user IDs other than add them to another group, so it hasn't come up much in the past.

**Comment by alexb-twingate** [comment]
Hi @Eforen - please let us know your use case! We're happy to make this change, we just want to make sure we're making the best possible change to support your use case.

Feel free to reopen this with your use case.
