### ISSUE TITLE
Add data source: `twingate_security_policy`

### ISSUE THREAD

**Issue by bertekintw** [Twingate/terraform-provider-twingate#62]

**Comment by ekampf** [comment]
As agreed on our meeting - lets start with just `id` and `name` 
We do want a single and plural datasources

**Comment by alexmensch** [comment]
> As agreed on our meeting - lets start with just `id` and `name`
> We do want a single and plural datasources

Just to clarify: for the plural datasource, we just need `id` and `name` outputs, and for the singular datasource, we will allow lookup by either `name` or `id`.
