### ISSUE TITLE
Enhance the existing twingate_group resource

### ISSUE THREAD

**Issue by bertekintw** [Twingate/terraform-provider-twingate#65]
**Modified functionality**

_Arguments_

- (Optional) `users` of type `list(string)`
    - List of user `id`s obtained from the `twingate_user` or `twingate_users` data sources.
- (Optional) `resources` of type `list(string)`
    - List of resource `id`s obtained from the `twingate_resource` or `twingate_resources` data sources.

_Notes_

- Creating a new group must use the `GroupCreate` mutation and future group modifications must use the `GroupUpdate` mutation.
- In `GroupUpdate` the existing `addedResourceIds`, `addedUserIds`, `removedResourceIds`, and `removedUserIds` arguments allow applying delta changes to users and groups already, so this should work well with the provider logic & implementation.

**Comment by alexmensch** [comment]
Closing in favor of #221
