### ISSUE TITLE
Enhance the existing twingate_resource resource

### ISSUE THREAD

**Issue by bertekintw** [Twingate/terraform-provider-twingate#66]
**Modified functionality**

_Arguments_

- (Optional) `remote_network` of type `string`
    - Takes a single `twingate_remote_network` data source `id` as an argument.
- (Optional) `groups` of type `list(string)`
    - List of group `id`s obtained from the `twingate_group` or `twingate_groups` data sources.

_Notes_

- Creating a new resource must use the `ResourceCreate` mutation and future group modifications must use `ResourceUpdate`.
- In `ResourceUpdate` the existing `addedGroupIds` and `removedGroupIds` arguments allow applying delta changes to groups already, so this should work well with the provider logic & implementation.
- Finally, we already have an argument called `remote_network_id` which takes as its input the remote network ID directly from our API. If there’s an official way to mark a parameter as deprecated, we should mark this parameter that way, otherwise we’ll have to make the documentation very clear to draw attention to the fact that it will not accept Terraform ids for resources. Any other ideas on how to make this less confusing are welcome.

**Comment by ekampf** [comment]
@alexmensch why would we use `addedGroupIds` and `removedGroupIds` ?  TF knows the state it expects the resource to be at so it doesn't need to calculate deltas but use the `groupIds` arg
