### ISSUE TITLE
Add the ability to create and configure service accounts

### ISSUE THREAD

**Issue by bertekintw** [Twingate/terraform-provider-twingate#67]
**Create a new `twingate_service_account` resource**

**New functionality**

Arguments

- (Required) `name` of type `string`
    - What the service account will be called in Twingate.

Notes

- We will not allow setting assigned resources here and instead require using the `twingate_resources_service_account_assign` and `twingate_resources_service_account_add` resources.

Example usage

```terraform
resource "twingate_service_account" "github_actions_prod" {
	name = "Github Actions PROD"
}
```

**Create a new `twingate_service_account_key` resource**

**New functionality**

Arguments

- (Required) `service_account_id` of type `string`
    - The `id` of the `twingate_service` resource that the key is assigned to.
- (Optional) `name` of type `string`
    - What the service key will be called in Twingate. If no name is assigned, Twingate will randomly generate a name.

Example usage

```terraform
resource "twingate_service_account" "github_actions_prod" {
  name = "Github Actions PROD"
}

resource "twingate_service__accountkey" "github_actions_prod" {
  service_id = twingate_service_account.github_actions_prod.id
}
```

**Comment by badsector3** [comment]
Any updates on that? Do we have any ETA when can be expect the resource to be added to the provider?

**Comment by alexmensch** [comment]
Hey @badsector3 we're working through the issues in Stage 1 and 2 milestones first, which we're thinking will take us into mid-July, and then we'll be tackling these issues in Stage 3 after that. We'll be making updates in this issue, so feel free to follow it.

**Comment by ekampf** [comment]
@vmanilo lets start with the 2 resources:
- Resource `twingate_service_account`
  - field `name`
- Resource `twingate_service_account_key`
  - field `name`
  - field `service_account_id`
  - field `expiration_time` 


Afterwards we need to model the `service-account <> resource` relationship

**Comment by vmanilo** [comment]
On the call we discussed changes for Resource `twingate_service_account_key`
* add `status` field
* remove `expiration_time`
* uses zero expiration value for now

**Comment by alexmensch** [comment]
Hey @vmanilo I updated the issue description to reflect the changes we'd like to make here. Just some minor changes (eg. the name of the resource), otherwise should be in line with the PRs you're working on already.

**Comment by vmanilo** [comment]
got it, will update resource and field names
