### ISSUE TITLE
When supplying an empty port range with the "RESTRICTED" policy option in the twingate_resource.protocols resource definition, the provider crashes

### ISSUE THREAD

**Issue by alexmensch** [Twingate/terraform-provider-twingate#77]
Expected behavior: this configuration is valid and the provider should not crash. Per our public API behavior, when supplying an empty port list in the "RESTRICTED" policy mode, traffic on all ports will be blocked.

Let me know if you need reproduction steps @vmanilo

**Comment by vmanilo** [comment]
the issue is clear, what would be the expected output?
to return error msg `empty port range`?

**Comment by alexmensch** [comment]
Ah yeah, sorry, I'll edit the original description. But this is actually valid, so it should be accepted without crashing and simply block all ports on the relevant protocol.

When an empty port range is supplied in our API with the "RESTRICTED" policy option, this means that all ports are blocked. This is similar to the "DENY_ALL" issue, which is just a shortcut for this same combination of "RESTRICTED" with an empty port range.

**Comment by vmanilo** [comment]
@alexmensch I've manage to reproduce crash only with configuration like this, did you mean this case?

```
tcp  {
      policy = "RESTRICTED"
      ports = [""]
    }
```

**Comment by vmanilo** [comment]
and also this crashes 

```
ports = ["", "80"]
```

so, basically if we have at least one empty string, we can ignore all other ports in the list, right?

**Comment by vmanilo** [comment]
btw, when passing values like this

```
      policy = "RESTRICTED"
      ports = [" "]
```

backend converts it to "ALLOW_ALL" (see this value when fetching resource)

**Comment by vmanilo** [comment]
should I keep policy name **RESTRICTED**, or I need to change it to **DENY_ALL**?

**Comment by ekampf** [comment]
@vmanilo no it doesn't need to change.
You should look at the GraphQL docs for `ProtocolsInput` (and maybe they're not clear enough and we need to fix them?):
![Screen Shot 2022-04-22 at 1 01 23 PM](https://user-images.githubusercontent.com/205185/164785699-9cc761c0-7adc-43aa-ae8c-cb2599fa7b50.png)

So `ProtocolsInput` has 2 "modes":
1. `ALLOW_ALL` in which case all ports are allowed and we dont even look at the `ports` value
2. `RESTRICTED` in which only traffic to certain ports is allowed, per the definition in the `ports` field.

If a customer wants to restrict all access to a protocol he would need to specify:
```
policy = "RESTRICTED"
ports = []
```

Which means ports are restricted to the list specified in `ports` which is an empty list == no ports allowed

**Comment by ekampf** [comment]
`""` value in `ports` shouldn't be valid

**Comment by ekampf** [comment]
Alsowhat happens in the case of other non valid ports values?  like `["foo"]` ?

**Comment by alexmensch** [comment]
> and also this crashes
> 
> ```
> ports = ["", "80"]
> ```
> 
> so, basically if we have at least one empty string, we can ignore all other ports in the list, right?

Just to clarify, I think there are a few things here when using the `RESTRICTED` policy:
1. `ports = ["", "80"]` is a little ambiguous in terms of what the user intended, so if we see an empty value in the list, ie. `""`, then we should consider the input invalid as @ekampf said.
2. If we see `ports = [""]` then it seems like the user intent is really `ports = []` which is an empty list. In this case also just rejecting `""` an an invalid value will solve this problem.
3. Lastly, the `DENY_ALL` policy is something we should fix as part of issue #70. The idea is that `DENY_ALL` is a shortcut for `policy = "RESTRICTED"; ports = []`, which just makes using the provider clearer for the end user.

**Comment by vmanilo** [comment]
thank you guys!

@ekampf in case use provides in port range some invalid values like "   " or "foo", backend change policy type from RESTRICTED to ALLOW_ALL

to summarise if user provides some invalid port range value we should return error msg back right? 
with empty list it currently works without crashing

we could validate ports range values with regexp like this `^\d+(-\d+)?`, right?

**Comment by ekampf** [comment]
@vmanilo yes that regexp looks right

@alexmensch when you say [""] should be treated as [] you are basically saying you want to filter out invalid values before parsing and making the call?
While technically possible I don't think it should be done.
We should behave like developers expect and give meaningful error when you send erroneous values rather try act smart about it.

**Comment by alexmensch** [comment]
> @alexmensch when you say [""] should be treated as [] you are basically saying you want to filter out invalid values before parsing and making the call?
> While technically possible I don't think it should be done.
> We should behave like developers expect and give meaningful error when you send erroneous values rather try act smart about it.
>  

No, I'm not saying that at all. I said in my comment --> "In this case also just rejecting "" an an invalid value will solve this problem." I meant by "rejecting" that it should generate an error.

We should generate errors for erroneous input as you're saying. I was just trying to point out what the likely intent is for someone doing one of those things.
